version: 2
jobs:
  build:
    working_directory: ~/oice-server
    docker:
      - image: python:3.6-alpine
    environment:
      - CI: "true"
      - TERM: dumb
    steps:
      - run: apk add --no-cache curl git gzip tar
      - checkout
      - restore_cache:
          key: oice-server-{{ checksum "requirements.txt" }}
      - run:
          name: Kafka-Depencies
          command: |
              apk --no-cache --virtual .build-deps add \
                bash \
                gcc \
                g++ \
                linux-headers \
                make \
                openssl\
                && mkdir /rdkafka \
                && cd /rdkafka \
                && wget https://github.com/edenhill/librdkafka/archive/v0.9.2.tar.gz \
                && tar xvzf v0.9.2.tar.gz \
                && cd librdkafka-0.9.2 \
                && ./configure --prefix=/usr \
                && make -j4 \
                && make install \
                && ldconfig /usr/local/lib \
                && apk del .build-deps \
                && rm -rf /rdkafka
      - run:
          name: Dependencies
          command: |
            apk --no-cache --virtual .build-deps add gcc g++ musl-dev linux-headers
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python setup.py develop
      - save_cache:
          key: oice-server-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Start Test
          command: |
            . venv/bin/activate
            pserve example.ini
          background: true
      - run:
          name: Curl Test
          command: |
            sleep 5
            curl --retry 10 --retry-delay 5 -v http://localhost:6543/
