version: 2
jobs:
  build:
    working_directory: ~/oice-server
    docker:
      - image: python:3.9-alpine
    environment:
      - CI: "true"
      - TERM: dumb
    steps:
      - run: apk add --no-cache curl git gzip tar
      - checkout
      - restore_cache:
          key: oice-server-{{ checksum "requirements.txt" }}
      - run:
          name: Dependencies
          command: |
            apk --no-cache --virtual .build-deps add gcc g++ musl-dev linux-headers
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install setuptools==45
            python setup.py develop
      - save_cache:
          key: oice-server-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Start Test
          command: |
            . venv/bin/activate
            pserve example.ini
          background: true
      - run:
          name: Curl Test
          command: |
            sleep 5
            curl --retry 10 --retry-delay 5 -v http://localhost:6543/
